nodeLinker: node-modules

# エディタサポートとツールチェーン互換性を向上
pnpEnableEsmLoader: false

# Yarn 4の設定
compressionLevel: mixed
enableGlobalCache: false
enableMirror: true
enableNetwork: true
enableScripts: true
enableStrictSsl: true
enableTelemetry: false

# パッケージエクステンション
packageExtensions:
  react-dom@*:
    peerDependencies:
      react: '*'
